# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for git submodules
  - package-ecosystem: "gitsubmodule"
    # Look for `.gitmodules` in the `root` directory
    directory: "/"
    pull-request-branch-name:
      separator: "-"
    # Check the submodules for updates every week
    schedule:
      interval: "weekly"
      day: "friday"
      time: "07:00"
      timezone: "Europe/Berlin"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Look for `*.yml` files in the `.github/workflows` directory
    directory: "/"
    pull-request-branch-name:
      separator: "-"
    # Check for updates to GitHub Actions every week
    schedule:
      interval: "weekly"
      day: "friday"
      time: "07:00"
      timezone: "Europe/Berlin"

  # Keep packages.json up-to-date
  - package-ecosystem: "npm"
    directory: "/"
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "07:00"
      timezone: "Europe/Berlin"
